name: 'Serverless GithubAction'
description: Github action for Serverless Framework with Node 12 and latest Serverless Framework
inputs:
  command:
    description: 'Serverless command including arguments'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.args }}
branding:
  icon: 'zap' 
  color: orange
